### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by AlexEAA** [aviacommerce/avia#493]
trying to collect docker

/config/docker/dev/Dockerfile-dev

Step 21/28 : COPY mix.exs mix.lock ./
COPY failed: stat /var/lib/docker/tmp/docker-builder074448497/mix.exs: no such file or directory

**Comment by AlexEAA** [comment]
As a result, I chose an image, can someone help make docker compose I don’t quite understand how all these modules interact

seoinetru/eccomerce:latest

**Comment by AlexEAA** [comment]
```
version: '2'
services:
  eccomerce:
    image: seoinetru/eccomerce:latest
    container_name: eccomerce
    networks:
      - frontend
      - backend
    expose:
      - 4000   
    #volumes:
      #- /root/compose/mysite/avia:/avia-backend/
    labels:
      - "traefik.backend=eccomerce"
      - "traefik.docker.network=frontend"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:domain.ru,www.domain.ru"
      - "traefik.port=4000"
    environment:
      - ENV ELASTIC_HOST elasticsearch
      - ENV DB_HOST db  
    ports:
      #- "4000:4000"
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - kibana
    links:
      - db
      - elasticsearch
      - kibana
  db:
    image: postgres:10
    container_name: db
    networks:
      - backend  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snitch_dev
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - backend      
    ports:
      - "9200:9200"
      
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - backend    
     
     
     
networks:
  frontend:
    external:
      name: frontend
  backend:
    external:
      name: backend
```
